In [1]:
import pandas as pd

df = pd.read_csv("../input/customer-analytics/Train.csv")
df.head()

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,1,D,Flight,4,2,177,3,low,F,44,1233,1
1,2,F,Flight,4,5,216,2,low,M,59,3088,1
2,3,A,Flight,2,2,183,4,low,M,48,3374,1
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1

In [7]:
df['Reached.on.Time_Y.N'].unique()

array([1, 0])

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10999 entries, 0 to 10998
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   10999 non-null  int64
 1   Warehouse_block      10999 non-null  object
 2   Mode_of_Shipment     10999 non-null  object
 3   Customer_care_calls  10999 non-null  int64
 4   Customer_rating      10999 non-null  int64
 5   Cost_of_the_Product  10999 non-null  int64
 6   Prior_purchases      10999 non-null  int64
 7   Product_importance   10999 non-null  object
 8   Gender               10999 non-null  object
 9   Discount_offered     10999 non-null  int64
 10  Weight_in_gms        10999 non-null  int64
 11  Reached.on.Time_Y.N  10999 non-null  int64
dtypes: int64(8), object(4)
memory usage: 1.0+ MB

In [12]:
data = df.iloc[:,1:-1]
target = df.iloc[:,-1]

In [14]:
df['Warehouse_block'].unique()

array(['D', 'F', 'A', 'B', 'C'], dtype=object)

In [15]:
df['Mode_of_Shipment'].unique()

array(['Flight', 'Ship', 'Road'], dtype=object)

In [16]:
df['Product_importance'].unique()

array(['low', 'medium', 'high'], dtype=object)

In [17]:
df['Gender'].unique()

array(['F', 'M'], dtype=object)

- 라벨 인코딩

In [32]:
from sklearn.preprocessing import LabelEncoder

for obj in data.columns[data.dtypes=='object']:
    encoder = LabelEncoder()
    data[obj] = encoder.fit_transform(data[obj])

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10999 entries, 0 to 10998
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Warehouse_block      10999 non-null  int64
 1   Mode_of_Shipment     10999 non-null  int64
 2   Customer_care_calls  10999 non-null  int64
 3   Customer_rating      10999 non-null  int64
 4   Cost_of_the_Product  10999 non-null  int64
 5   Prior_purchases      10999 non-null  int64
 6   Product_importance   10999 non-null  int64
 7   Gender               10999 non-null  int64
 8   Discount_offered     10999 non-null  int64
 9   Weight_in_gms        10999 non-null  int64
dtypes: int64(10)
memory usage: 859.4 KB

- 학습/테스트 데이터

In [34]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target,
                                                   test_size=0.2, random_state=2022)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train,
                                                   test_size=0.2, random_state=2022)

In [35]:
X_train.shape, X_val.shape, X_test.shape

((7039, 10), (1760, 10), (2200, 10))

- 모델 학습

In [57]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=300, max_depth=5)
model.fit(X_train, y_train)
pred = model.predict(X_test)

- 모델 평가

In [58]:
from sklearn.metrics import accuracy_score, roc_auc_score

roc_auc_score(y_test, pred)

0.7230284573373006

In [59]:
accuracy_score(y_test, pred)

0.6786363636363636

In [63]:
output = pd.DataFrame({'pred':pred})

In [66]:
output.to_csv('1234567.csv', index=False)

In [67]:
pd.read_csv('1234567.csv')

      pred
0        0
1        0
2        0
3        0
4        1
...    ...
2195     1
2196     0
2197     0
2198     0
2199     0

[2200 rows x 1 columns]